name: PR Checks

on:
  pull_request:
    branches: [ main ]

##
# Re-usable workflows can be found at https://github.com/modusbox/github-actions-node
##

jobs:
  test_lint:
    uses: modusbox/github-actions-node/.github/workflows/testLintJob.yml@v0.0.4

  test_dependencies:
    uses: modusbox/github-actions-node/.github/workflows/testDependencyJob.yml@v0.0.4

  test_audit:
    uses: modusbox/github-actions-node/.github/workflows/testAuditJob.yml@v0.0.4

  test_license:
    uses: modusbox/github-actions-node/.github/workflows/testLicenseJob.yml@v0.0.4

# TODO: Uncomment if unit tests added
#   test_unit:
#     uses: modusbox/github-actions-node/.github/workflows/testUnitJob.yml@v0.0.4

# TODO: Test coverage applies to unit tests and since there is none is commentted out
#   test_coverage:
#     uses: modusbox/github-actions-node/.github/workflows/testCoverageJob.yml@v0.0.4

  test_int:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node@${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - run: npm ci
      - run: |
          npm run backend:start
          nc -zv localhost 8233
          npm run test:int
#      - run: npm run backend:start
#      - run: nc -zv localhost 8233
#      - run: npm run test:int
      - run: npm run backend:stop
#  test_int:
#    uses: modusbox/github-actions-node/.github/workflows/testIntJob.yml@v0.0.4

  test_func:
    uses: ./.github/workflows/testFuncJob.yml
