name: PR Checks

on:
  pull_request:
    branches: [ main ]

##
# Re-usable workflows can be found at https://github.com/modusbox/github-actions-node
##

jobs:
  test_lint:
    uses: modusbox/github-actions-node/.github/workflows/testLintJob.yml@v0.0.4

  test_dependencies:
    uses: modusbox/github-actions-node/.github/workflows/testDependencyJob.yml@v0.0.4

  test_audit:
    uses: modusbox/github-actions-node/.github/workflows/testAuditJob.yml@v0.0.4

  test_license:
    uses: modusbox/github-actions-node/.github/workflows/testLicenseJob.yml@v0.0.4

# TODO: Uncomment if unit tests added
#   test_unit:
#     uses: modusbox/github-actions-node/.github/workflows/testUnitJob.yml@v0.0.4

# TODO: Test coverage applies to unit tests and since there is none is commentted out
#   test_coverage:
#     uses: modusbox/github-actions-node/.github/workflows/testCoverageJob.yml@v0.0.4

  test_int:
    uses: modusbox/github-actions-node/.github/workflows/testIntJob.yml@v0.0.4

  test_func:
    uses: ./.github/workflows/testFuncJob.yml
