name: Create Tagged Release

on:
  release:
    types: [published]
  push:
    branches:
      - main

##
# Re-usable workflows can be found at https://github.com/modusbox/github-actions-node
##

jobs:
  test_lint:
    uses: modusbox/github-actions-node/.github/workflows/testLintJob.yml@v0.0.4

  test_dependencies:
    uses: modusbox/github-actions-node/.github/workflows/testDependencyJob.yml@v0.0.4

  test_audit:
    uses: modusbox/github-actions-node/.github/workflows/testAuditJob.yml@v0.0.4

  test_license:
    uses: modusbox/github-actions-node/.github/workflows/testLicenseJob.yml@v0.0.4

  # TODO: Enable when there are unit tests
  #   test_unit:
  #     uses: modusbox/github-actions-node/.github/workflows/testUnitJob.yml@v0.0.4

  # TODO: Enable when there is coveragte for unit tests
  #   test_coverage:
  #     uses: modusbox/github-actions-node/.github/workflows/testCoverageJob.yml@v0.0.4

  test_int:
    uses: modusbox/github-actions-node/.github/workflows/testIntJob.yml@v0.0.4

  test_func:
    uses: ./.github/workflows/testFuncJob.yml


  publish_image:
    uses: modusbox/github-actions-node/.github/workflows/publishImageJob.yml@v0.0.2
    with:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
      RELEASE_URL: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}
    secrets:
      USER: ${{ github.actor }}
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}

